In [196]:
!pip install nltk
!pip install beautifulsoup4
!pip install tabulate

!pip install pandas


In [197]:
import pandas as pd
from collections import Counter
import nltk
from nltk.stem import SnowballStemmer
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer
import matplotlib.pyplot as plt
import seaborn as sns
import time
import string
import requests
import nltk
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from tabulate import tabulate

from bs4 import BeautifulSoup
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

# 1. Use the corpus you created in homework 1

In [198]:
# Define the URL of the Wikipedia page for Selkirk Rex
url = "https://en.wikipedia.org/wiki/Selkirk_Rex"

# Send a GET request to the URL
response = requests.get(url)

# Parse the HTML content of the page
soup = BeautifulSoup(response.content, 'html.parser')

# Find the container element that holds the main content of the page
content_div = soup.find('div', {'class': 'mw-parser-output'})

# Find all <p> tags within the content area
if content_div:
    paragraphs = content_div.find_all('p')

    # Extract text from each paragraph and concatenate them into a single string
    text_data = ''
    for paragraph in paragraphs:
        text_data += paragraph.get_text()

    # Print the scraped text data
    print(text_data)
    all_words = text_data.split()
else:
    print("Main content container not found.")

The Selkirk Rex is a breed of cat with highly curled hair.[1]
The Selkirk Rex is distinct from all other Rex breeds. Unlike the Devon Rex and Cornish Rex, the hair is of normal length and not partly missing. There are longhair and shorthair varieties.[2] It differs from the LaPerm in that the Selkirk Rex coat is plusher and thicker. While the LaPerm gene is a simple dominant, the Selkirk gene (Se) acts as an incomplete dominant; incompletely dominant allele pairs produce three possible genotypes and phenotypes: heterozygous cats (Sese) may have a fuller coat that is preferred in the show ring, while homozygous cats (SeSe) may have a tighter curl and less coat volume.
The Selkirk Rex originated in Montana, USA in 1987, with a litter born to a rescued cat.[3] The only unusually coated kitten in the litter was ultimately placed with breeder, Jeri Newman, who named her Miss DiPesto (after a curly-haired character in the TV series Moonlighting played by Allyce Beasley). This foundation cat 

 # 2. tokenization

**White Space Tokenizer**

In [199]:

def whitespace_tokenize(text):
    tokens = text.split()
    return tokens

# Example usage:
tokens_whitespace = whitespace_tokenize(text_data)
print(tokens_whitespace[:100])


['The', 'Selkirk', 'Rex', 'is', 'a', 'breed', 'of', 'cat', 'with', 'highly', 'curled', 'hair.[1]', 'The', 'Selkirk', 'Rex', 'is', 'distinct', 'from', 'all', 'other', 'Rex', 'breeds.', 'Unlike', 'the', 'Devon', 'Rex', 'and', 'Cornish', 'Rex,', 'the', 'hair', 'is', 'of', 'normal', 'length', 'and', 'not', 'partly', 'missing.', 'There', 'are', 'longhair', 'and', 'shorthair', 'varieties.[2]', 'It', 'differs', 'from', 'the', 'LaPerm', 'in', 'that', 'the', 'Selkirk', 'Rex', 'coat', 'is', 'plusher', 'and', 'thicker.', 'While', 'the', 'LaPerm', 'gene', 'is', 'a', 'simple', 'dominant,', 'the', 'Selkirk', 'gene', '(Se)', 'acts', 'as', 'an', 'incomplete', 'dominant;', 'incompletely', 'dominant', 'allele', 'pairs', 'produce', 'three', 'possible', 'genotypes', 'and', 'phenotypes:', 'heterozygous', 'cats', '(Sese)', 'may', 'have', 'a', 'fuller', 'coat', 'that', 'is', 'preferred', 'in', 'the']


**Word Tokenizer**

In [200]:

def tokenize_with_nltk(text):
    tokens = word_tokenize(text)
    tokens = [token for token in tokens if token not in string.punctuation]
    return tokens

# Example usage:
tokens_nltk = tokenize_with_nltk(text_data)
print(tokens_nltk[:100])


['The', 'Selkirk', 'Rex', 'is', 'a', 'breed', 'of', 'cat', 'with', 'highly', 'curled', 'hair', '1', 'The', 'Selkirk', 'Rex', 'is', 'distinct', 'from', 'all', 'other', 'Rex', 'breeds', 'Unlike', 'the', 'Devon', 'Rex', 'and', 'Cornish', 'Rex', 'the', 'hair', 'is', 'of', 'normal', 'length', 'and', 'not', 'partly', 'missing', 'There', 'are', 'longhair', 'and', 'shorthair', 'varieties', '2', 'It', 'differs', 'from', 'the', 'LaPerm', 'in', 'that', 'the', 'Selkirk', 'Rex', 'coat', 'is', 'plusher', 'and', 'thicker', 'While', 'the', 'LaPerm', 'gene', 'is', 'a', 'simple', 'dominant', 'the', 'Selkirk', 'gene', 'Se', 'acts', 'as', 'an', 'incomplete', 'dominant', 'incompletely', 'dominant', 'allele', 'pairs', 'produce', 'three', 'possible', 'genotypes', 'and', 'phenotypes', 'heterozygous', 'cats', 'Sese', 'may', 'have', 'a', 'fuller', 'coat', 'that', 'is', 'preferred']


 **Regex Tokenizer**

In [201]:
import time
from nltk.tokenize import RegexpTokenizer

def regex_tokenize(text, pattern=r'\w+'):
    tokenizer = RegexpTokenizer(pattern)
    tokens = tokenizer.tokenize(text)
    return tokens

# Example usage:
tokens_regex = regex_tokenize(text_data)
print(tokens_regex[:100])


['The', 'Selkirk', 'Rex', 'is', 'a', 'breed', 'of', 'cat', 'with', 'highly', 'curled', 'hair', '1', 'The', 'Selkirk', 'Rex', 'is', 'distinct', 'from', 'all', 'other', 'Rex', 'breeds', 'Unlike', 'the', 'Devon', 'Rex', 'and', 'Cornish', 'Rex', 'the', 'hair', 'is', 'of', 'normal', 'length', 'and', 'not', 'partly', 'missing', 'There', 'are', 'longhair', 'and', 'shorthair', 'varieties', '2', 'It', 'differs', 'from', 'the', 'LaPerm', 'in', 'that', 'the', 'Selkirk', 'Rex', 'coat', 'is', 'plusher', 'and', 'thicker', 'While', 'the', 'LaPerm', 'gene', 'is', 'a', 'simple', 'dominant', 'the', 'Selkirk', 'gene', 'Se', 'acts', 'as', 'an', 'incomplete', 'dominant', 'incompletely', 'dominant', 'allele', 'pairs', 'produce', 'three', 'possible', 'genotypes', 'and', 'phenotypes', 'heterozygous', 'cats', 'Sese', 'may', 'have', 'a', 'fuller', 'coat', 'that', 'is', 'preferred']


**Sentence Tokenizer**

In [202]:
import time
from nltk.tokenize import sent_tokenize

def sentence_tokenize(text):
    sentences = sent_tokenize(text)
    return sentences

# Example usage:
sentences = sentence_tokenize(text_data)
print(sentences[:10])


['The Selkirk Rex is a breed of cat with highly curled hair.', '[1]\nThe Selkirk Rex is distinct from all other Rex breeds.', 'Unlike the Devon Rex and Cornish Rex, the hair is of normal length and not partly missing.', 'There are longhair and shorthair varieties.', '[2] It differs from the LaPerm in that the Selkirk Rex coat is plusher and thicker.', 'While the LaPerm gene is a simple dominant, the Selkirk gene (Se) acts as an incomplete dominant; incompletely dominant allele pairs produce three possible genotypes and phenotypes: heterozygous cats (Sese) may have a fuller coat that is preferred in the show ring, while homozygous cats (SeSe) may have a tighter curl and less coat volume.', 'The Selkirk Rex originated in Montana, USA in 1987, with a litter born to a rescued cat.', '[3] The only unusually coated kitten in the litter was ultimately placed with breeder, Jeri Newman, who named her Miss DiPesto (after a curly-haired character in the TV series Moonlighting played by Allyce Bea

# 3. Normalization

 **NLTK Lemmatization**

In [203]:
def lemmatize_text(text):
    # Initialize WordNet Lemmatizer
    lemmatizer = WordNetLemmatizer()

    # Lemmatize the text
    lemmatized_words = [lemmatizer.lemmatize(word) for word in nltk.word_tokenize(text) if word not in string.punctuation]

    return lemmatized_words

lemmatized_words = lemmatize_text(text_data)
print(lemmatized_words[:100])


['The', 'Selkirk', 'Rex', 'is', 'a', 'breed', 'of', 'cat', 'with', 'highly', 'curled', 'hair', '1', 'The', 'Selkirk', 'Rex', 'is', 'distinct', 'from', 'all', 'other', 'Rex', 'breed', 'Unlike', 'the', 'Devon', 'Rex', 'and', 'Cornish', 'Rex', 'the', 'hair', 'is', 'of', 'normal', 'length', 'and', 'not', 'partly', 'missing', 'There', 'are', 'longhair', 'and', 'shorthair', 'variety', '2', 'It', 'differs', 'from', 'the', 'LaPerm', 'in', 'that', 'the', 'Selkirk', 'Rex', 'coat', 'is', 'plusher', 'and', 'thicker', 'While', 'the', 'LaPerm', 'gene', 'is', 'a', 'simple', 'dominant', 'the', 'Selkirk', 'gene', 'Se', 'act', 'a', 'an', 'incomplete', 'dominant', 'incompletely', 'dominant', 'allele', 'pair', 'produce', 'three', 'possible', 'genotype', 'and', 'phenotype', 'heterozygous', 'cat', 'Sese', 'may', 'have', 'a', 'fuller', 'coat', 'that', 'is', 'preferred']


**Stemming using NLTK**

In [204]:
def stem_text_nltk(text):
    # Initialize PorterStemmer
    stemmer = PorterStemmer()

    # Stem the text
    stemmed_words = [stemmer.stem(word) for word in word_tokenize(text) if word not in string.punctuation]

    return stemmed_words

stemmed_words = stem_text_nltk(text_data)
print(stemmed_words[:100])


['the', 'selkirk', 'rex', 'is', 'a', 'breed', 'of', 'cat', 'with', 'highli', 'curl', 'hair', '1', 'the', 'selkirk', 'rex', 'is', 'distinct', 'from', 'all', 'other', 'rex', 'breed', 'unlik', 'the', 'devon', 'rex', 'and', 'cornish', 'rex', 'the', 'hair', 'is', 'of', 'normal', 'length', 'and', 'not', 'partli', 'miss', 'there', 'are', 'longhair', 'and', 'shorthair', 'varieti', '2', 'it', 'differ', 'from', 'the', 'laperm', 'in', 'that', 'the', 'selkirk', 'rex', 'coat', 'is', 'plusher', 'and', 'thicker', 'while', 'the', 'laperm', 'gene', 'is', 'a', 'simpl', 'domin', 'the', 'selkirk', 'gene', 'se', 'act', 'as', 'an', 'incomplet', 'domin', 'incomplet', 'domin', 'allel', 'pair', 'produc', 'three', 'possibl', 'genotyp', 'and', 'phenotyp', 'heterozyg', 'cat', 'sese', 'may', 'have', 'a', 'fuller', 'coat', 'that', 'is', 'prefer']


# 4. Remove Stop Words

In [205]:
import nltk
from nltk.corpus import stopwords

# Download the stopwords dataset
nltk.download('stopwords')

def remove_stop_words(tokens):
    # Get the list of English stop words
    stop_words = set(stopwords.words('english'))
    
    # Filter out stop words from the token list
    filtered_tokens = [token for token in tokens if token.lower() not in stop_words]
    
    return filtered_tokens

# Remove stop words
filtered_tokens = remove_stop_words(tokens_nltk)

print(filtered_tokens[:100])


['Selkirk', 'Rex', 'breed', 'cat', 'highly', 'curled', 'hair', '1', 'Selkirk', 'Rex', 'distinct', 'Rex', 'breeds', 'Unlike', 'Devon', 'Rex', 'Cornish', 'Rex', 'hair', 'normal', 'length', 'partly', 'missing', 'longhair', 'shorthair', 'varieties', '2', 'differs', 'LaPerm', 'Selkirk', 'Rex', 'coat', 'plusher', 'thicker', 'LaPerm', 'gene', 'simple', 'dominant', 'Selkirk', 'gene', 'Se', 'acts', 'incomplete', 'dominant', 'incompletely', 'dominant', 'allele', 'pairs', 'produce', 'three', 'possible', 'genotypes', 'phenotypes', 'heterozygous', 'cats', 'Sese', 'may', 'fuller', 'coat', 'preferred', 'show', 'ring', 'homozygous', 'cats', 'SeSe', 'may', 'tighter', 'curl', 'less', 'coat', 'volume', 'Selkirk', 'Rex', 'originated', 'Montana', 'USA', '1987', 'litter', 'born', 'rescued', 'cat', '3', 'unusually', 'coated', 'kitten', 'litter', 'ultimately', 'placed', 'breeder', 'Jeri', 'Newman', 'named', 'Miss', 'DiPesto', 'curly-haired', 'character', 'TV', 'series', 'Moonlighting', 'played']


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


# 5. feature extraction

### Bag of Words (BoW)

In [206]:

# Import necessary libraries
from sklearn.feature_extraction.text import CountVectorizer

# Define sample corpus of documents
corpus = sentences
# Create an instance of CountVectorizer with default settings
vectorizer = CountVectorizer()

# Fit the vectorizer on the corpus and transform the corpus into a BOW matrix
bow_matrix = vectorizer.fit_transform(corpus)

# Print the BOW matrix
print(bow_matrix.toarray())

# Print the feature names (i.e., unique words) learned by the vectorizer
print(vectorizer.get_feature_names_out()[:100])

print("------------------------------------------------------------")

def get_most_frequent_words(X, vectorizer, top_n=10):
    # Sum up the counts of each vocabulary word
    word_counts = np.asarray(X.sum(axis=0)).flatten()
    
    # Get the indices that would sort the array in descending order
    sorted_indices = np.argsort(word_counts)[::-1]
    
    # Get the feature names (words)
    feature_names = vectorizer.get_feature_names_out()
    
    # Get the top N most frequent words
    most_frequent_words = [(feature_names[idx], word_counts[idx]) for idx in sorted_indices[:top_n]]
    
    return most_frequent_words

# Get the most frequent words
most_frequent_words = get_most_frequent_words(bow_matrix, vectorizer, top_n=10)
print("Most Frequent Words:", most_frequent_words)


[[0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]
['10' '1987' '1992' '1998' '2000' '2015' '21' 'abnormality' 'accepted'
 'acts' 'actual' 'adwh' 'after' 'albinism' 'all' 'allele' 'allelic'
 'allergens' 'allergic' 'allyce' 'also' 'american' 'amounts' 'an'
 'ancestry' 'and' 'are' 'as' 'associated' 'association' 'australia'
 'autosomal' 'back' 'bathing' 'be' 'beasley' 'been' 'bicolors' 'black'
 'born' 'break' 'bred' 'breed' 'breeder' 'breeders' 'breeding' 'breeds'
 'british' 'built' 'by' 'can' 'cardiomyopathy' 'cat' 'cats' 'cfa'
 'character' 'characterized' 'chocolate' 'cinnamon' 'coat' 'coated'
 'colors' 'copies' 'cornish' 'council' 'creases' 'crucial' 'cuddly' 'curl'
 'curled' 'curls' 'curly' 'currently' 'defined' 'demonstrated' 'dense'
 'dermatitis' 'designation' 'develop' 'developed' 'development' 'devon'
 'differs' 'dipesto' 'discontinued' 'disease' 'diseases' 'disqualifiable'
 'distinct' 'dominant' 'down' 'ducts' 

### TF-IDF - words

In [207]:

def tfidf_extraction(corpus):
    vectorizer = TfidfVectorizer()
    X = vectorizer.fit_transform(corpus)
    return X, vectorizer

# Example usage:
X_tfidf, vectorizer_tfidf = tfidf_extraction(filtered_tokens)
print("TF-IDF Feature Names:", vectorizer_tfidf.get_feature_names_out()[:100])
print("TF-IDF Features:\n", X_tfidf.toarray())
# Print the first row of the TF-IDF feature matrix
print("First row of the TF-IDF Features:\n", X_tfidf.toarray()[0])

TF-IDF Feature Names: ['10' '1987' '1992' '1998' '2000' '2015' '21' 'abnormality' 'accepted'
 'acts' 'actual' 'adwh' 'albinism' 'allele' 'allelic' 'allergens'
 'allergic' 'allyce' 'also' 'american' 'amounts' 'ancestry' 'associated'
 'association' 'australia' 'autosomal' 'back' 'bathing' 'beasley'
 'bicolors' 'black' 'born' 'break' 'bred' 'breed' 'breeder' 'breeders'
 'breeding' 'breeds' 'british' 'built' 'cardiomyopathy' 'cat' 'cats' 'cfa'
 'character' 'characterized' 'chocolate' 'cinnamon' 'coat' 'coated'
 'colors' 'copies' 'cornish' 'council' 'creases' 'crucial' 'cuddly' 'curl'
 'curled' 'curls' 'curly' 'currently' 'defined' 'demonstrated' 'dense'
 'dermatitis' 'designation' 'develop' 'developed' 'development' 'devon'
 'differs' 'dipesto' 'discontinued' 'disease' 'diseases' 'disqualifiable'
 'distinct' 'dominant' 'ducts' 'ear' 'ears' 'equal' 'except' 'excessive'
 'exotic' 'extreme' 'extremely' 'eyes' 'face' 'fanciers' 'fancy' 'fault'
 'feel' 'first' 'follicle' 'forming' 'found' 'foun

### TF-IDF - sentences

In [208]:

def tfidf_extraction(corpus):
    vectorizer = TfidfVectorizer()
    X = vectorizer.fit_transform(corpus)
    return X, vectorizer

# Example usage:
X_tfidf, vectorizer_tfidf = tfidf_extraction(sentences)
print("TF-IDF Feature Names:", vectorizer_tfidf.get_feature_names_out())
print("TF-IDF Features:\n", X_tfidf.toarray())

TF-IDF Feature Names: ['10' '1987' '1992' '1998' '2000' '2015' '21' 'abnormality' 'accepted'
 'acts' 'actual' 'adwh' 'after' 'albinism' 'all' 'allele' 'allelic'
 'allergens' 'allergic' 'allyce' 'also' 'american' 'amounts' 'an'
 'ancestry' 'and' 'are' 'as' 'associated' 'association' 'australia'
 'autosomal' 'back' 'bathing' 'be' 'beasley' 'been' 'bicolors' 'black'
 'born' 'break' 'bred' 'breed' 'breeder' 'breeders' 'breeding' 'breeds'
 'british' 'built' 'by' 'can' 'cardiomyopathy' 'cat' 'cats' 'cfa'
 'character' 'characterized' 'chocolate' 'cinnamon' 'coat' 'coated'
 'colors' 'copies' 'cornish' 'council' 'creases' 'crucial' 'cuddly' 'curl'
 'curled' 'curls' 'curly' 'currently' 'defined' 'demonstrated' 'dense'
 'dermatitis' 'designation' 'develop' 'developed' 'development' 'devon'
 'differs' 'dipesto' 'discontinued' 'disease' 'diseases' 'disqualifiable'
 'distinct' 'dominant' 'down' 'ducts' 'ear' 'ears' 'equal' 'except'
 'excessive' 'exotic' 'extreme' 'extremely' 'eyes' 'face' 'fanciers'

### Word Embedding by Word2Vec

In [209]:

# Tokenize the corpus
tokenized_corpus = [word_tokenize(doc.lower()) for doc in filtered_tokens]

# Define corpus
corpus = tokenized_corpus


# Train the Word2Vec model
model = Word2Vec(
    sentences=corpus,      # The corpus to train the model on
    vector_size=100,       # The size of the word vectors to be learned
    window=5,              # The size of the window of words to be considered
    min_count=5,           # The minimum frequency required for a word to be included in the vocabulary
    sg=0,                  # 0 for CBOW, 1 for skip-gram
    negative=5,            # The number of negative samples to use for negative sampling
    ns_exponent=0.75,      # The exponent used to shape the negative sampling distribution
    alpha=0.03,            # The initial learning rate
    min_alpha=0.0007,      # The minimum learning rate to which the learning rate will be linearly reduced
    epochs=30,             # The number of epochs (iterations) over the corpus
    workers=4,             # The number of worker threads to use for training the model
    seed=42,               # The seed for the random number generator
    max_vocab_size=None    # The maximum vocabulary size (None means no limit)
)

# Get the vector representation of a word
vector = model.wv['cat']

# Find the most similar words to a given word
similar_words = model.wv.most_similar('cat')

# Print the vector and similar words
print("Vector for 'cat':", vector)
print("Most similar words to 'cat':", similar_words)


Vector for 'cat': [-2.6747298e-03  8.1716133e-03 -9.8687407e-05  3.9941417e-03
 -8.5165142e-04 -4.6826019e-03  5.2845883e-03  9.3835266e-03
 -4.7295033e-03  5.5750180e-03 -4.7772001e-03  4.3378030e-03
  5.7801306e-03 -1.0127712e-03  4.7383918e-03 -4.5551695e-03
 -8.4149297e-03 -8.0721816e-03 -1.0595262e-03  8.0520473e-03
 -7.4484632e-03 -8.8447449e-04  4.0806402e-03 -5.9527336e-03
  4.4323276e-03 -3.8808680e-03  6.1732149e-03  1.5843904e-03
  9.3814492e-04 -6.4645447e-03 -7.3588250e-04  7.1322848e-03
 -9.6095204e-03  5.1703895e-03 -1.4475227e-04  4.3892586e-03
  3.2659601e-03 -1.3581396e-03 -3.8266564e-03  2.5461756e-03
 -7.1955156e-03  1.6819584e-03 -8.1061069e-03  2.9969311e-03
  2.5749051e-03 -8.3111143e-03  5.1497580e-03 -1.6838526e-03
  5.7377289e-03 -9.1677178e-03 -6.4108707e-03 -1.2018442e-04
 -6.2354971e-03 -3.4027768e-03  3.2119798e-03 -7.1095168e-03
  3.5540580e-03 -7.9319421e-03 -6.4962972e-03  1.7528903e-03
  5.8696638e-03 -6.5881405e-03 -4.0001450e-03  8.5024023e-03
  9.79

## 6. What is GloVe?

GloVe (Global Vectors for Word Representation) is an unsupervised learning algorithm for obtaining vector representations for words. It combines the advantages of both the global matrix factorization and local context window methods to generate word embeddings. Developed by researchers at Stanford, GloVe aims to capture the global statistical information of a corpus while preserving the contextual information of words.

In [210]:

# Load GloVe vectors
def load_glove_model(glove_file):
    print("Loading Glove Model")
    glove_model = {}
    with open(glove_file, 'r', encoding='utf-8') as f:
        for line in f:
            split_line = line.split()
            word = split_line[0]
            embedding = np.array([float(val) for val in split_line[1:]])
            glove_model[word] = embedding
    print(f"Done. {len(glove_model)} words loaded!")
    return glove_model

# Path to the GloVe file 
glove_file = r"C:\Users\USER\Downloads\glove.6B\glove.6B.100d.txt"

# Load the GloVe model
glove_model = load_glove_model(glove_file)

# Function to get the GloVe embedding for a word
def get_glove_embedding(word, glove_model):
    return glove_model.get(word, np.zeros(100))

# Example usage
word = 'cat'
word_embedding = get_glove_embedding(word, glove_model)
print(f"GloVe vector for '{word}':\n", word_embedding)

# Apply GloVe embeddings to the tokenized corpus
corpus_embeddings = []
for doc in corpus:
    doc_embeddings = [get_glove_embedding(word, glove_model) for word in doc]
    corpus_embeddings.append(doc_embeddings)

# Print the embeddings for the first document
print(f"Embeddings for the first document:\n {corpus_embeddings[0]}")


Loading Glove Model
Done. 400001 words loaded!
GloVe vector for 'cat':
 [ 0.23088    0.28283    0.6318    -0.59411   -0.58599    0.63255
  0.24402   -0.14108    0.060815  -0.7898    -0.29102    0.14287
  0.72274    0.20428    0.1407     0.98757    0.52533    0.097456
  0.8822     0.51221    0.40204    0.21169   -0.013109  -0.71616
  0.55387    1.1452    -0.88044   -0.50216   -0.22814    0.023885
  0.1072     0.083739   0.55015    0.58479    0.75816    0.45706
 -0.28001    0.25225    0.68965   -0.60972    0.19578    0.044209
 -0.31136   -0.68826   -0.22721    0.46185   -0.77162    0.10208
  0.55636    0.067417  -0.57207    0.23735    0.4717     0.82765
 -0.29263   -1.3422    -0.099277   0.28139    0.41604    0.10583
  0.62203    0.89496   -0.23446    0.51349    0.99379    1.1846
 -0.16364    0.20653    0.73854    0.24059   -0.96473    0.13481
 -0.0072484  0.33016   -0.12365    0.27191   -0.40951    0.021909
 -0.6069     0.40755    0.19566   -0.41802    0.18636   -0.032652
 -0.78571   -0

### **Explanation of the Results**

**GloVe Vector for "cat"**
- Vector Representation: The array represents the word "cat" in a 100-dimensional space. Each value in the vector encodes some aspect of the word's meaning and relationships with other words.
- Semantic Information: Vectors that are close in this high-dimensional space correspond to words that are semantically similar. For example, the vector for "cat" will be close to vectors for "dog," "pet," or "animal."

**Document Embeddings:**

- The document embedding is obtained by averaging (a;though this is not the only method) the vectors of all words in the document that have corresponding GloVe vectors.
- This approach creates a single vector that represents the entire document, making it suitable for tasks like document classification, clustering, and similarity analysis.
- The agregated vector covers the overall semantic content of the text: the meaning, theme and semantic nuances based on the words the text contains.

In [211]:

def cyk_parse(sentence, grammar):
    tokens = sentence.lower().split()
    n = len(tokens)
    table = [[set() for _ in range(n+1)] for _ in range(n+1)]

    # Initialization
    for i in range(1, n+1):
        for rule in grammar:
            if len(rule) == 2 and rule[1] == tokens[i-1]:
                table[i][i].add(rule[0])

    # Rule Application
    for length in range(2, n+1):
        for i in range(1, n-length+2):
            j = i + length - 1
            for k in range(i, j):
                for rule in grammar:
                    if len(rule) == 3:
                        if rule[1] in table[i][k] and rule[2] in table[k+1][j]:
                            table[i][j].add(rule[0])
                    elif len(rule) == 4:
                        for m in range(k+1, j):
                            if rule[1] in table[i][k] and rule[2] in table[k+1][m] and rule[3] in table[m+1][j]:
                                table[i][j].add(rule[0])

    # Check if the start symbol is in the top-right cell
    if 'S' in table[1][n]:
        return True, table
    else:
        return False, table

# Define the updated context-free grammar in CNF
grammar = [
    ('S', 'NP', 'VP'),
    ('VP', 'V', 'NP'),
    ('VP', 'V', 'PP'),
    ('VP', 'V', 'NP', 'PP'),
    ('NP', 'Det', 'N'),
    ('NP', 'N'),
    ('PP', 'P', 'NP'),
    ('Det', 'the'),
    ('Det', 'a'),
    ('N', 'dog'),
    ('N', 'bird'),
    ('N', 'garden'),
    ('V', 'saw'),
    ('V', 'chased'),
    ('V', 'played'),
    ('P', 'in'),
    ('P', 'with')
]

# List of input sentences to be parsed
sentences = [
    "a bird chased the dog in the garden",
    "A dog saw the bird",
    "The bird saw the dog in the garden",
    "a dog played in the garden",
    "a dog played with a bird"
]
# Call the CYK parser
for sentence in sentences:
    parsed, table = cyk_parse(sentence, grammar)
    
    # Print the parse table and whether the sentence was parsed or not
    if parsed:
        print("Input sentence: ", sentence)
        print("Parse table: ")
       
        n = len(table) - 1
        headers = [''] + [str(i) for i in range(1, n + 1)]
        rows = []
        for i in range(1, n + 1):
            row = [str(i)]
            for j in range(1, n + 1):
                row.append(", ".join(sorted(table[i][j])))
            rows.append(row)
        print(tabulate(rows, headers=headers, tablefmt='grid'))
        print("\n*********************************************************\n")
    else:
        print("Input sentence: ", sentence)
        print("Sentence not parsed.")

Input sentence:  a bird chased the dog in the garden
Parse table: 
+----+-----+-----+-----+-----+-----+-----+-----+-----+
|    | 1   | 2   | 3   | 4   | 5   | 6   | 7   | 8   |
+====+=====+=====+=====+=====+=====+=====+=====+=====+
|  1 | Det | NP  |     |     | S   |     |     | S   |
+----+-----+-----+-----+-----+-----+-----+-----+-----+
|  2 |     | N   |     |     |     |     |     |     |
+----+-----+-----+-----+-----+-----+-----+-----+-----+
|  3 |     |     | V   |     | VP  |     |     | VP  |
+----+-----+-----+-----+-----+-----+-----+-----+-----+
|  4 |     |     |     | Det | NP  |     |     |     |
+----+-----+-----+-----+-----+-----+-----+-----+-----+
|  5 |     |     |     |     | N   |     |     |     |
+----+-----+-----+-----+-----+-----+-----+-----+-----+
|  6 |     |     |     |     |     | P   |     | PP  |
+----+-----+-----+-----+-----+-----+-----+-----+-----+
|  7 |     |     |     |     |     |     | Det | NP  |
+----+-----+-----+-----+-----+-----+-----+-----+-----